[package]
name = "zescrow-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "The Zescrow client CLI for cross-chain escrow operations"
readme = "README.md"

[features]
default = []
prover = ["dep:zescrow-prover"]

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
alloy = { version = "2.0.5", features = ["signer-local"] }
anchor-client = "1.0.2"
anchor-lang = "1.0.2"
bincode = { workspace = true }
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15"
hex = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
solana-client = "3"
solana-sdk = "3"
thiserror = { workspace = true }
tokio = { version = "1", features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
url = { version = "2.5", features = ["std"] }
zescrow-core = { workspace = true, features = ["bincode", "json"] }
zescrow-prover = { workspace = true, optional = true }
escrow = { path = "../agent/solana/escrow/programs/escrow", features = [
    "no-entrypoint",
] }
