[package]
name = "zescrow-prover"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "RISC Zero zkVM prover for Zescrow"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
risc0-ethereum-contracts = "3"
risc0-zkvm = { version = "3", features = ["unstable"] }
thiserror = { workspace = true }
tracing = { workspace = true }
zescrow-core = { workspace = true, features = ["bincode", "json"] }
zescrow-methods = { workspace = true }

[dev-dependencies]
sha2 = { workspace = true }
