[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "J4SfUoLAAsvmAWMQGa8dJHw8vsSvRfUUMXGTxcmSeS8s"
mock_verifier = "6JvFfBrvCcWgANKh1Eae9xDq4RC6cfJuBcf71rp2k9Y7"

[programs.devnet]
escrow = "J4SfUoLAAsvmAWMQGa8dJHw8vsSvRfUUMXGTxcmSeS8s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path harness/Cargo.toml"
